source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.1"

gem "pg", "~> 1.1"
gem "rails", "~> 6.1.7", ">= 6.1.7.3"

# Vite
gem "vite_rails", "~> 3.0", ">= 3.0.14"

# Haml support
gem "haml-rails", "~> 2.0"

gem "puma", "~> 5.0"

gem "bootsnap", ">= 1.4.4", require: false

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails", "~> 6.0.0"
  gem "shoulda-matchers", "~> 5.0"
  gem "factory_bot_rails", "~> 6.2"
end

group :development do
  gem 'annotate', '~> 2.7', '>= 2.7.1'
  gem "listen", "~> 3.3"
  gem "rack-mini-profiler", "~> 2.0"
  gem "spring"
  gem "web-console", ">= 4.1.0"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
